### PR TITLE
New sample - my flows list

### PR DESCRIPTION
**Pull request by Adam-it**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                                |
| New feature?    | no                               |
| New sample?     | yes                               |

## What's in this Pull Request?
👋 hi there, 

Could I contribute with a new sample 😉? very simple react application customizer that presents the user flow list. 

👉The main requirement behind this functionality was to give the users additional place to see what is running, what failed and what passed (together with some flow details) without having to leave the SP site to the Power Automate dashboard. This sample presents the basic concept (starting point) which may be extended further 🤔.

### CODE REVIEW

**Comment by Adam-it** [comment]
@hugoabernier thanks for the update commit 👍👍. Will pay more attention for the additional info in the readme in the future 😉

**Comment by hugoabernier** [comment]
Thanks @Adam-it! How would you feel about presenting this sample on the January 27th SPFx community call? You'd have 10-13 minutes to show the application extension and the code.

**Comment by Adam-it** [comment]
@hugoabernier thanks for the opportunity 👍👍 but how about some later (currently not defined) date 😉? I am gonna have a bigger family soon and it will be more or less around that day 😉.

**Comment by hugoabernier** [comment]
Not a problem at all @Adam-it -- and congratulations! Let me know when you're ready and we'll schedule something.

**Pull request merged**
