### PR TITLE
New sample : Copy PnP Search results webpart settings

### PR DESCRIPTION
**Pull request by anoopt**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no                               |
| New sample?     | yes                               |
| Related issues? | NA |

## What's in this Pull Request?

Contains a new list view command set to copy settings of PnP Search results webpart from one page to another.

### CODE REVIEW

**Comment by hugoabernier** [comment]
Thank you @anoopt. Very cool idea -- and very useful.

Would you be interested in talking about the PnP search web part settings and how this extension is used, and how it works in a 10-13 minute demo on the July 1st community call?

**Comment by anoopt** [comment]
Thank you @hugoabernier . Yes, happy to do a demo of this on 1st of July.

**Comment by hugoabernier** [comment]
Perfect @anoopt, I have you confirmed on the agenda for July 1. Looking forward to your demo.

**Comment by anoopt** [comment]
@hugoabernier - Sorry, I just realised that the debug url in the README.md file is set to `ClientSideExtension.ApplicationCustomizer` instead of `ClientSideExtension.ListViewCommandSet.CommandBar`. Do you want me to submit a new PR for that or do you mind updating that?

**Comment by hugoabernier** [comment]
No worries @hugoabernier, I made the changes. It gave me an opportunity to try [Visual Studio Code Remote Repositories](https://marketplace.visualstudio.com/items?itemName=github.remotehub).

**Comment by anoopt** [comment]
Ah yes! Brilliant!

**Pull request merged**
