### PR TITLE
creation of react-field-unique-permissions sample

### PR DESCRIPTION
**Pull request by mkm17**
> By submitting this pull request, you agree to the [contribution guidelines](https://github.com/pnp/sp-dev-fx-extensions/blob/main/CONTRIBUTING.md)

> If you aren't familiar with how to contribute to open-source repositories using GitHub, or if you find the instructions on this page confusing, [sign up](https://forms.office.com/Pages/ResponsePage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUREZVRDVYUUJLT1VNRDM4SjhGMlpUNzBORy4u) for one of our [Sharing is Caring](https://pnp.github.io/sharing-is-caring/#pnp-sic-events) events. It's completely free, and we'll guide you through the process.

|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                                |
| New feature?    | no                               |
| New sample?     | yes                               |
| Related issues? | no |

## What's in this Pull Request?

A new sample of SPFx customizer named "react-field-unique-permission" to manage unique item permissions on SharePoint List. 

Please don't hesitate to reach out if you have any questions.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
This is a cool implementation and a scenario and we'll get his merged soon for sure. We could though also schedule a community call demo for this if you'd be interested on showcasing the implementation. Please fill in following form and we'll get you scheduled - https://aka.ms/community/request/demo

Thank you for sharing your sample with others - highly appreciated 👏🥇👩‍💻

**Comment by mkm17** [comment]
Thank you @VesaJuvonen for your comment. I will definitely consider your proposal :)

**Comment by hugoabernier** [comment]
Thank you @mkm17 ! Much appreciated!

**Comment by mkm17** [comment]
Hi @hugoabernier , thank you very much for your review. Since it is my first contribution to the samples, I was wondering if there is anything that I need to sign or keep in mind?

**Pull request merged**
