### PR TITLE
Upgrage extension SPFx version to 1.12.1

### PR DESCRIPTION
**Pull request by mohammadamer**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                                |
| New feature?    | no                                |
| New sample?     | no                                |
| Related issues? |  no  |

## What's in this Pull Request?
Upgrade SPFx version to 1.12.1

### CODE REVIEW

**Comment by PaoloPia** [comment]
Hi @mohammadamer,
Thanks for your contribution.
Any chance you'd be interested in doing a live 10-15 min demo on this in our upcoming community calls? A good demo structure would be to have a few slides explaining the scenario and why it matters, then do a live demo and then move to code to show the key parts.

Would you be interested in this? Let us know. Thx

**Comment by mohammadamer** [comment]
Well, if you mean talking about upgrading SPFx old versions to new versions. Why not!
I'm just thinking to maybe talk about something more practical and important :)

**Comment by PaoloPia** [comment]
Actually, I was talking about demoing the sample, not how to upgrade the sample :-) ...

**Comment by mohammadamer** [comment]
Well, I'm not the sample author. I'll soon come with an interesting sample, and I'll ask for demoing it.

**Pull request merged**
