### PR TITLE
New Sample: News ticker

### PR DESCRIPTION
**Pull request by AriGunawan**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| New sample?     | yes                               |

## What's in this Pull Request?

Sample for news ticker on SharePoint page using SPFx extension application customizer.

### CODE REVIEW

**Comment by hugoabernier** [comment]
Thanks for taking the time to fill the PR template and providing a complete README.md. I'll process the PR this week!

**Comment by AriGunawan** [comment]
Awesome! 🎉

**Comment by hugoabernier** [comment]
** breaking news ** breaking news ** breaking news **
This is a very cool extension @AriGunawan!

Would you be interested in showing your sample in a 10-13 minutes demo on the June 3rd SPFx community call?

Also, we'd like to start giving the opportunity for contributors to write blog posts describing their solutions. The blog post would appear at aka.ms/m365pnp/community/blog. Would you be interested in writing such a post?

Feel free to DM me if you need more information.

**Comment by AriGunawan** [comment]
Thanks for the appreciation! 😀

Thanks for the offering for the demo but I think this sample doesn't have many things to show.
I would really love to do some demo in the community call but with something that has more value.

However, I'm interested in writing a post to describe this solution.
Just let me know how to submit a post to the community blog. Thanks!

**Comment by hugoabernier** [comment]
@AriGunawan that makes perfect sense. 

Just fill this form and you'll be set up as an author: [http://aka.ms/techcommunity-author](http://aka.ms/techcommunity-author)

I look forward to your post! And thanks again for your contribution.

**Comment by AriGunawan** [comment]
@hugoabernier thanks
I've filled in the form but I'm still not sure how to create a post.
Is it by starting a discussion?
image

Regarding this solution, I found that you might put the wrong author details in the sample.json for this solution
image

One last thing, I just got permission from my boss to submit my company logo to be displayed in the PnP release article when I contributed to the PnP community.
How can I submit my company logo for it?
Thanks in advance.

**Comment by hugoabernier** [comment]
Oops, I must've copied and pasted the author from my template and forgot to update it. Feel free to update it.

If you DM me about the other topics, I'll gladly set you up.

**Pull request merged**
