### PR TITLE
Add react feedback widget application customizer

### PR DESCRIPTION
**Pull request by Sandeep-FED**
> By submitting this pull request, you agree to the [contribution guidelines](https://github.com/pnp/sp-dev-fx-extensions/blob/main/CONTRIBUTING.md)

> If you aren't familiar with how to contribute to open-source repositories using GitHub, or if you find the instructions on this page confusing, [sign up](https://forms.office.com/Pages/ResponsePage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUREZVRDVYUUJLT1VNRDM4SjhGMlpUNzBORy4u) for one of our [Sharing is Caring](https://pnp.github.io/sharing-is-caring/#pnp-sic-events) events. It's completely free, and we'll guide you through the process.

|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                             |
| New feature?    | no                               |
| New sample?     | yes                               |
| Related issues? | N/A |

## What's in this Pull Request?

> An SPFx Application Customizer Extension placed in the bottom placeholder which allows users to input their feedbacks without scrolling down to the end of the page. SharePoint list is used to store the feedbacks submitted by the users. To enhance the appearance and interactivity lottie-react library used. Functionalities like props to passing data between components has implemented.

### CODE REVIEW

**Comment by Sandeep-FED** [comment]
Hi @hugoabernier ,
Please have look into this PR.

Regards,
Sandeep P S

**Comment by hugoabernier** [comment]
Thanks @Sandeep-FED . I'm getting errors when trying to build the sample. Can you share what version of Node.js you used when building this sample?

**Comment by Sandeep-FED** [comment]
Hi @hugoabernier , node version is 16.18.1, could you please send me the error screenshot or any info?

**Comment by hugoabernier** [comment]
Tried using 16.18.1 and getting the following errors:

```
Warning - [sass] The local CSS class 'feedback-widget-container' is not camelCase and will not be type-safe.
Warning - [sass] The local CSS class 'text-style' is not camelCase and will not be type-safe.
Warning - [sass] The local CSS class 'popup-container' is not camelCase and will not be type-safe.
Warning - [sass] The local CSS class 'slide-up' is not camelCase and will not be type-safe.
Warning - [sass] The local CSS class 'header-container' is not camelCase and will not be type-safe.
Error - [lint] Unexpected STDERR output from ESLint:
Oops! Something went wrong! :(
ESLint: 8.7.0
TypeError: Cannot read properties of undefined (reading 'getTokens')
Occurred while linting D:/GitHub/pnp/sp-dev-fx-extensions/samples/react-application-customizer-feedback-widget/src/extensions/feedback/components/FeedbackCustomizer.tsx:11
Rule: "@typescript-eslint/no-empty-function"
    at Object.reportIfEmpty (D:/GitHub/pnp/sp-dev-fx-extensions/samples/react-application-customizer-feedback-widget/node_modules/eslint/lib/rules/no-empty-function.js:142:46)
    at FunctionDeclaration (D:/GitHub/pnp/sp-dev-fx-extensions/samples/react-application-customizer-feedback-widget/node_modules/@microsoft/eslint-config-spfx/node_modules/@typescript-eslint/eslint-plugin/dist/rules/no-empty-function.js:156:23)
    at ruleErrorHandler (D:/GitHub/pnp/sp-dev-fx-extensions/samples/react-application-customizer-feedback-widget/node_modules/@microsoft/rush-stack-compiler-4.5/node_modules/eslint/lib/linter/linter.js:1079:28)
    at D:/GitHub/pnp/sp-dev-fx-extensions/samples/react-application-customizer-feedback-widget/node_modules/@microsoft/rush-stack-compiler-4.5/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (D:/GitHub/pnp/sp-dev-fx-extensions/samples/react-application-customizer-feedback-widget/node_modules/@microsoft/rush-stack-compiler-4.5/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (D:/GitHub/pnp/sp-dev-fx-extensions/samples/react-application-customizer-feedback-widget/node_modules/@microsoft/rush-stack-compiler-4.5/node_modules/eslint/lib/linter/node-event-generator.js:297:26)    
    at NodeEventGenerator.applySelectors (D:/GitHub/pnp/sp-dev-fx-extensions/samples/react-application-customizer-feedback-widget/node_modules/@microsoft/rush-stack-compiler-4.5/node_modules/eslint/lib/linter/node-event-generator.js:326:22)   
    at NodeEventGenerator.enterNode (D:/GitHub/pnp/sp-dev-fx-extensions/samples/react-application-customizer-feedback-widget/node_modules/@microsoft/rush-stack-compiler-4.5/node_modules/eslint/lib/linter/node-event-generator.js:340:14)        
    at CodePathAnalyzer.enterNode (D:/GitHub/pnp/sp-dev-fx-extensions/samples/react-application-customizer-feedback-widget/node_modules/@microsoft/rush-stack-compiler-4.5/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)

Error - [lint]
```

**Comment by Sandeep-FED** [comment]
@hugoabernier This will resolves the issue: `npm i -DE eslint@8.7.0`

**Comment by hugoabernier** [comment]
Thank you @Sandeep-FED for your sample! (And thank you for your patience!)

We'd love to have your sample featured in one of our future community calls.

If you'd be interested on showing this great sample in a public community call, please fill in following form and we'll get you scheduled - [aka.ms/community/request/demo](https://aka.ms/community/request/demo)

Thank you for sharing your sample with others - highly appreciated 👏🥇👩‍💻

**Pull request merged**
