### PR TITLE
Sample Upgraded to SPFx v1.10.0

### PR DESCRIPTION
**Pull request by rahulsuryawanshi**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no                               |
| New sample?     | no                               |
| Upgrade existing sample?     | yes                               |

## What's in this Pull Request?

> Original sample is upgraded to SharePoint Framework version 1.10.0.
>

### CODE REVIEW

**Comment by rahulsuryawanshi** [comment]
Upgraded original sample I submitted to latest SharePoint Framework version 1.10.0. Please review and let me know if any questions / concerns.

**Comment by hugoabernier** [comment]
Thanks @rahulsuryawanshi for keeping this very useful sample up-to-date.

**Comment by rahulsuryawanshi** [comment]
Hi @hugoabernier,
Thanks for approving the pull request! Based on your and David @PopWarner  guidence from #SharingIsCaring, I have started learning how to contribute. I believe my pull request was OK and doesn't need lot of changes.

**Comment by hugoabernier** [comment]
@rahulsuryawanshi it was perfect thank you!

**Comment by rahulsuryawanshi** [comment]
Excellent! Thanks for your guidance.

Thanks
Rahul

On Jun 18, 2020, at 6:04 PM, Hugo Bernier <notifications@github.com> wrote:

﻿

@rahulsuryawanshi<https://github.com/rahulsuryawanshi> it was perfect thank you!

**Pull request merged**
