### PR TITLE
Added sample 'react-company-templates'

### PR DESCRIPTION
**Pull request by tmaestrini**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                              |
| New feature?    | no |
| New sample?     | yes?                               |

## What's in this Pull Request?

New SPFx extension sample that provides access to centrally managed company templates (from a document library in SharePoint Online) and makes them available in every document library. It makes use of several NPM packages, such as  PnPJs and SPFx React Controls and demonstrates a modern UI experience.

### CODE REVIEW

**Comment by hugoabernier** [comment]
Many thanks @tmaestrini for your sample! Highly appreciated!

We'd love to have your sample featured in one of our future community calls.

If haven't done so yet, and you'd be interested on showing this great sample in a public community call, please fill in following form and we'll get you scheduled - [aka.ms/community/request/demo](https://aka.ms/community/request/demo)

Thank you for sharing your sample with others - you rock! 👏🥇👩‍💻

**Comment by tmaestrini** [comment]
Thanks to YOU, @hugoabernier. Your feedback made me really happy! 🙌

**Comment by tmaestrini** [comment]
@hugoabernier One last question :)
When I do a search query containing "tobias maestrini" or "tobias.maestrini" or "tmaestrini" in the SharePoint Framework (SPFx) Samples repository, there's only one result:
image

Do you know why?

**Comment by hugoabernier** [comment]
Yeah, the automated merging of sample metadata is currently broken. It should still show them on adoption.Microsoft.com, but the SPFx samples browser is currently stuck. I'm working on a fix.

**Comment by tmaestrini** [comment]
Thank you for your feedback, no problems! Adoption.microsoft.com works fine 👌 - but shouldn't there also be a mention for the "react personal tools" (https://github.com/pnp/sp-dev-fx-webparts/pull/4746)
Sorry for this questions, I'm just asking. 😇

**Pull request merged**
