### PR TITLE
New Sample: React Message Banner

### PR DESCRIPTION
**Pull request by pmatthews05**
> By submitting this pull request, you agree to the [contribution guidelines](https://github.com/pnp/sp-dev-fx-extensions/blob/main/CONTRIBUTING.md)

> If you aren't familiar with how to contribute to open-source repositories using GitHub, or if you find the instructions on this page confusing, [sign up](https://forms.office.com/Pages/ResponsePage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUREZVRDVYUUJLT1VNRDM4SjhGMlpUNzBORy4u) for one of our [Sharing is Caring](https://pnp.github.io/sharing-is-caring/#pnp-sic-events) events. It's completely free, and we'll guide you through the process.

|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                             |
| New feature?    | no                    |
| New sample?     | yes                               |
| Related issues? | n/a |

## What's in this Pull Request?

A react Message Banner sample, allows to add a custom banner message to your SharePoint Online modern sites. Can target either Site or Web Scoped. Allows a site owner to modify the text, font size, colours and height of the banner. Specify a start date to control when the banner is visible to members of a site.  Uses the latest v1.15.2 of SPFX framework.

### CODE REVIEW

**Comment by PaoloPia** [comment]
Hi @pmatthews05, I'm on it! Thanks!

**Comment by PaoloPia** [comment]
Great job @pmatthews05! It is now merged! Thanks for your contribution.

Any chance you'd be interested in doing a live 10-15 min demo on this in our upcoming community calls? A good demo structure would be to have a few slides explaining the scenario and why it matters, then do a live demo and then move to code to show the key parts.

Would you be interested in this? Let us know. Thx

**Comment by pmatthews05** [comment]
Hi @PaoloPia, thank you for the offer of doing a demo in upcoming community call. 
If I did, it would have to be in a few weeks time. I'll look up when your next community call is and watch as a viewer first and decide from there.

**Comment by PaoloPia** [comment]
If you will be interested, please submit your interest through this form: https://aka.ms/m365pnp/request/demo . Thanks!

**Pull request merged**
