### PR TITLE
react list addfolders

### PR DESCRIPTION
**Pull request by michaelmaillot**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no                               |
| New sample?     | yes                               |
| Related issues? | no |

## What's in this Pull Request?

This sample shows how to add multiple folders in a row (nested or not), from anywhere in a list or a library.

### CODE REVIEW

**Comment by hugoabernier** [comment]
Thank you @michaelmaillot, this is great! 

I hope you don't mind, but I renamed the project to be consistent with the repository's naming convention.

Would you be interested in demoing this extension on our Feb 25 SharePoint Framework [community call](https://pnp.github.io/#community)?

**Comment by michaelmaillot** [comment]
Sure, why not!

Is there a template for the slides, or some other guidances to follow for the demo?

**Comment by michaelmaillot** [comment]
I just realized that the version history in the README file indicates 2020 instead of 2021... 😬 

Should I push a fix here or through another PR?

**Comment by hugoabernier** [comment]
No worries, I can do it. Thanks again!

**Comment by hugoabernier** [comment]
> I just realized that the version history in the README file indicates 2020 instead of 2021... 😬
> 
> Should I push a fix here or through another PR?

Thanks @michaelmaillot I just updated it. I usually write the wrong year on dates all the way until about June or July :-)

> Sure, why not!

That's wonderful. I have you confirmed for the 25th of Feb. Looking forward to your demo!

> Is there a template for the slides, or some other guidances to follow for the demo?

There isn't a template, really, because people are most interested in:
a) Who you are
b) What was the purpose of your sample (i.e.: "what's in it for me?")
c) The demo
d) The key areas of code.
e) Where to find out more

I wrote a [demo checklist](https://tahoeninjas.blog/2021/01/04/my-demo-checklist-for-pnp-calls/) -- mostly for myself -- but it may give help you get ready for the call.

If you need a PowerPoint template, DM me via Twitter and I'll set you up.

> Oh BTW, the template for the README.md file mentions links to the old site of the docs here. Could be nice to update it to be redirected to Microsoft Docs 🙂

Thanks! I'll fix it right away!

**Pull request merged**
